"""empty message

Revision ID: 345117aa53e4
Revises: 7bba2d6450b7
Create Date: 2023-04-06 14:26:01.466829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345117aa53e4'
down_revision = '7bba2d6450b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins', sa.Integer(), nullable=True))
        batch_op.drop_column('points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.INTEGER(), nullable=True))
        batch_op.drop_column('coins')

    # ### end Alembic commands ###
