"""empty message

Revision ID: 7bba2d6450b7
Revises: ed6c77ddc181
Create Date: 2023-04-06 12:39:34.284220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bba2d6450b7'
down_revision = 'ed6c77ddc181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprite', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sprite')

    # ### end Alembic commands ###
