"""empty message

Revision ID: f21c320cb067
Revises: f97e87669799
Create Date: 2023-04-14 11:10:08.968402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21c320cb067'
down_revision = 'f97e87669799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sound')
        batch_op.drop_column('ghost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ghost', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('sound', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
